version: "3"
services:
  apollo:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 196309159802.dkr.ecr.us-west-2.amazonaws.com/techindex:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - "4000:4000"
    command: ["yarn", "dev"]
    environment:
      - RHOST=redis
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: '[ $$(redis-cli ping) = "PONG" ] || exit 1 ]'
      timeout: 2s
      interval: 5s
      retries: 5
volumes:
  redis:
