apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: graphql-service
spec:
  hosts:
  - "*"
  gateways:
  - prisma-gateway
  http:
  - match:
      - uri: 
          prefix: /apollo
    route:
    - destination:
        host: graphql-service
        port:
          number: 80