apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: graphql-service
spec:
  hosts:
  - "scti.ok8s.net"
  gateways:
  - prisma-gateway
  http:
  - match:
      - uri: 
          exact: /apollo
    route:
    - destination:
        host: graphql-service
        port:
          number: 80