apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  labels:
    stage: production
    name: prisma
    app: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    managementApiSecret: xxx
    # enableManagementApi: true
    # rabbitUri: amqp://user:password@wrinkled-pike-rabbitmq.default.svc.cluster.local:5672
    # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
    # managementApiSecret: my-secret
    databases:
      default:
        connector: postgres
        host: builtin-prom-postgres-replicas
        port: 5432
        user: prisma
        password: prisma
        migrations: true
