apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-service
  labels:
    app: graphql-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: graphql-service
  template:
    metadata:
      labels:
        app: graphql-service
    spec:
      containers:
        - name: graphql-service
          image: gcr.io/stanfordcodextextindex/scitapollo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              name: http-server
            - containerPort: 433
              name: https-server
